version: '3.8'

services:
  bot:
    build: .
    container_name: sakura_bot
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - VALKEY_URL=valkey://valkey:6379
      - DATABASE_URL=postgresql://user:password@db:5432/sakuradb
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OWNER_ID=${OWNER_ID}
      - SUPPORT_LINK=${SUPPORT_LINK}
      - UPDATE_LINK=${UPDATE_LINK}
      - PING_LINK=${PING_LINK}
    ports:
      - "10000:10000"
    depends_on:
      - db
      - valkey
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: sakura_db
    environment:
      - POSTGRES_DB=sakuradb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  valkey:
    image: valkey/valkey:7.2
    container_name: sakura_valkey
    restart: unless-stopped
    volumes:
      - valkey_data:/data

volumes:
  postgres_data:
  valkey_data: